#pure_pursuit/pure_pursuit_controller_node
lookahead_dist: 1.0
buffer_length: 50
v_max: 0.5
delta_t: 0.5
offset: 0.15

yellow_num_points: 5
yellow_points_memory_secs: 1.0 
yellow_points_max_distance: 2.0
yellow_max_buffer_size: 500
